"""Minimal scalar-field bridge for kernel-mediated memory dynamics.

The current Gaussian kernel can be represented exactly as a heat-flow
propagator in an auxiliary diffusion coordinate. A local relaxation-diffusion
mediator has a different stationary Green function. This module keeps those
two statements explicit instead of identifying them implicitly.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np


def _positive(name: str, value: float) -> float:
    number = float(value)
    if not np.isfinite(number) or number <= 0.0:
        raise ValueError(f"{name} must be positive")
    return number


@dataclass(frozen=True)
class RelaxationDiffusionField:
    """Parameters of ``tau*d_t phi=D*Delta phi-mu*phi+g*source``."""

    diffusivity: float
    decay_rate: float
    coupling: float = 1.0
    relaxation_time: float = 1.0

    def __post_init__(self) -> None:
        _positive("diffusivity", self.diffusivity)
        _positive("decay_rate", self.decay_rate)
        _positive("relaxation_time", self.relaxation_time)
        if not np.isfinite(self.coupling):
            raise ValueError("coupling must be finite")

    @property
    def correlation_length(self) -> float:
        """Return the stationary field length ``sqrt(D/mu)``."""

        return float(np.sqrt(self.diffusivity / self.decay_rate))

    @property
    def zero_mode_gain(self) -> float:
        """Return the stationary response at wave number zero."""

        return float(self.coupling / self.decay_rate)


def gaussian_transfer(wavenumber: np.ndarray, *, length: float) -> np.ndarray:
    """Return the zero-mode-normalized Gaussian Fourier multiplier."""

    scale = _positive("length", length)
    k = np.asarray(wavenumber, dtype=float)
    if not np.isfinite(k).all():
        raise ValueError("wavenumber must be finite")
    return np.exp(-0.5 * np.square(scale * k))


def heat_transfer(
    wavenumber: np.ndarray,
    *,
    diffusivity: float,
    diffusion_time: float,
) -> np.ndarray:
    """Return the Fourier multiplier generated by a heat equation."""

    diffusivity = _positive("diffusivity", diffusivity)
    diffusion_time = _positive("diffusion_time", diffusion_time)
    k = np.asarray(wavenumber, dtype=float)
    if not np.isfinite(k).all():
        raise ValueError("wavenumber must be finite")
    return np.exp(-diffusivity * diffusion_time * np.square(k))


def gaussian_heat_time(*, length: float, diffusivity: float = 1.0) -> float:
    """Return the heat time whose propagator has Gaussian width ``length``."""

    length = _positive("length", length)
    diffusivity = _positive("diffusivity", diffusivity)
    return float(length * length / (2.0 * diffusivity))


def stationary_field_transfer(
    wavenumber: np.ndarray,
    field: RelaxationDiffusionField,
    *,
    normalize_zero_mode: bool = False,
) -> np.ndarray:
    """Return the stationary Green multiplier ``g/(mu+D*k^2)``."""

    k = np.asarray(wavenumber, dtype=float)
    if not np.isfinite(k).all():
        raise ValueError("wavenumber must be finite")
    response = field.coupling / (field.decay_rate + field.diffusivity * np.square(k))
    if normalize_zero_mode:
        if field.zero_mode_gain == 0.0:
            raise ValueError("cannot normalize a field with zero coupling")
        response = response / field.zero_mode_gain
    return np.asarray(response, dtype=float)


def low_wavenumber_matched_field(
    *,
    gaussian_length: float,
    decay_rate: float = 1.0,
    coupling: float = 1.0,
    relaxation_time: float = 1.0,
) -> RelaxationDiffusionField:
    """Match the Gaussian and stationary field through order ``k^2``.

    ``exp(-L^2 k^2/2)`` and ``1/(1+L_phi^2 k^2)`` have equal quadratic
    terms for ``L_phi=L/sqrt(2)``.
    """

    gaussian_length = _positive("gaussian_length", gaussian_length)
    decay_rate = _positive("decay_rate", decay_rate)
    return RelaxationDiffusionField(
        diffusivity=decay_rate * gaussian_length**2 / 2.0,
        decay_rate=decay_rate,
        coupling=coupling,
        relaxation_time=relaxation_time,
    )
