"""Local one-dimensional mediator laws for controlled propagation tests.

The spatial coordinate represents the source-target axis. It is a numerical
transport channel, not a claim that the ambient state space is one-dimensional.
Both updates are local finite-difference Markov maps on their augmented field
states.
"""

from __future__ import annotations

from dataclasses import dataclass
import math
from typing import Iterable

import numpy as np


def _positive(name: str, value: float) -> float:
    number = float(value)
    if not math.isfinite(number) or number <= 0.0:
        raise ValueError(f"{name} must be positive and finite")
    return number


def _non_negative(name: str, value: float) -> float:
    number = float(value)
    if not math.isfinite(number) or number < 0.0:
        raise ValueError(f"{name} must be non-negative and finite")
    return number


@dataclass(frozen=True)
class LocalMediatorGrid:
    """Uniform 1D grid with the source fixed at one grid point."""

    spacing: float
    time_step: float
    points_left: int
    points_right: int

    def __post_init__(self) -> None:
        _positive("spacing", self.spacing)
        _positive("time_step", self.time_step)
        for name, value in (
            ("points_left", self.points_left),
            ("points_right", self.points_right),
        ):
            if isinstance(value, bool) or not isinstance(value, (int, np.integer)):
                raise ValueError(f"{name} must be an integer")
            if value < 2:
                raise ValueError(f"{name} must be at least two")

    @property
    def n_points(self) -> int:
        return int(self.points_left + self.points_right + 1)

    @property
    def source_index(self) -> int:
        return int(self.points_left)

    @property
    def coordinates(self) -> np.ndarray:
        return (
            np.arange(self.n_points, dtype=float) - float(self.source_index)
        ) * float(self.spacing)


@dataclass(frozen=True)
class RelaxationDiffusionMediator:
    """Parameters of ``d_t a = D d_xx a - mu a + s``."""

    diffusivity: float
    decay_rate: float

    def __post_init__(self) -> None:
        _positive("diffusivity", self.diffusivity)
        _non_negative("decay_rate", self.decay_rate)


@dataclass(frozen=True)
class TelegraphMediator:
    """Parameters of a damped local wave mediator.

    The field obeys

    ``d_tt a + 2*gamma*d_t a + omega_0^2*a = c^2*d_xx a + s``.
    """

    wave_speed: float
    damping_rate: float
    natural_frequency: float

    def __post_init__(self) -> None:
        _positive("wave_speed", self.wave_speed)
        _non_negative("damping_rate", self.damping_rate)
        _non_negative("natural_frequency", self.natural_frequency)


@dataclass(frozen=True)
class LocalMediatorTrace:
    """Field readouts generated by one local mediator update law."""

    model: str
    times: np.ndarray
    readout_positions: np.ndarray
    values: np.ndarray
    source_values: np.ndarray

    def __post_init__(self) -> None:
        times = np.asarray(self.times, dtype=float).copy()
        positions = np.asarray(self.readout_positions, dtype=float).copy()
        values = np.asarray(self.values, dtype=float).copy()
        source = np.asarray(self.source_values, dtype=float).copy()
        if times.ndim != 1 or times.size < 2 or not np.isfinite(times).all():
            raise ValueError("times must be a finite one-dimensional sequence")
        if positions.ndim != 1 or positions.size < 1:
            raise ValueError("readout_positions must be one-dimensional")
        if values.shape != (times.size, positions.size):
            raise ValueError("values must have shape (times, readout_positions)")
        if source.shape != (times.size - 1,):
            raise ValueError("source_values must have one value per update")
        if not np.isfinite(positions).all() or not np.isfinite(values).all():
            raise ValueError("mediator trace values must be finite")
        if not np.isfinite(source).all():
            raise ValueError("source_values must be finite")
        for array in (times, positions, values, source):
            array.setflags(write=False)
        object.__setattr__(self, "times", times)
        object.__setattr__(self, "readout_positions", positions)
        object.__setattr__(self, "values", values)
        object.__setattr__(self, "source_values", source)


def relaxation_diffusion_frequency_response(
    wavenumber: np.ndarray | float,
    angular_frequency: np.ndarray | float,
    mediator: RelaxationDiffusionMediator,
    *,
    normalize_static: bool = False,
) -> np.ndarray:
    """Return ``1/(D*k^2 + mu - i*omega)`` on broadcast inputs."""

    k, omega = np.broadcast_arrays(
        np.asarray(wavenumber, dtype=float),
        np.asarray(angular_frequency, dtype=float),
    )
    if not np.isfinite(k).all() or not np.isfinite(omega).all():
        raise ValueError("wavenumber and angular_frequency must be finite")
    static_denominator = mediator.diffusivity * np.square(k) + mediator.decay_rate
    denominator = static_denominator - 1j * omega
    if np.any(np.abs(denominator) == 0.0):
        raise ValueError("frequency response is singular at the requested mode")
    response = 1.0 / denominator
    if normalize_static:
        if np.any(static_denominator == 0.0):
            raise ValueError("cannot normalize a zero static denominator")
        response = static_denominator * response
    return np.asarray(response, dtype=np.complex128)


def telegraph_frequency_response(
    wavenumber: np.ndarray | float,
    angular_frequency: np.ndarray | float,
    mediator: TelegraphMediator,
    *,
    normalize_static: bool = False,
) -> np.ndarray:
    """Return the damped-wave response on broadcast mode/frequency inputs."""

    k, omega = np.broadcast_arrays(
        np.asarray(wavenumber, dtype=float),
        np.asarray(angular_frequency, dtype=float),
    )
    if not np.isfinite(k).all() or not np.isfinite(omega).all():
        raise ValueError("wavenumber and angular_frequency must be finite")
    static_denominator = (
        mediator.wave_speed**2 * np.square(k) + mediator.natural_frequency**2
    )
    denominator = (
        static_denominator
        - np.square(omega)
        - 2j * mediator.damping_rate * omega
    )
    if np.any(np.abs(denominator) == 0.0):
        raise ValueError("frequency response is singular at the requested mode")
    response = 1.0 / denominator
    if normalize_static:
        if np.any(static_denominator == 0.0):
            raise ValueError("cannot normalize a zero static denominator")
        response = static_denominator * response
    return np.asarray(response, dtype=np.complex128)


def rectangular_source(
    n_steps: int,
    *,
    pulse_steps: int,
    amplitude: float = 1.0,
) -> np.ndarray:
    """Return a finite rectangular source pulse."""

    if isinstance(n_steps, bool) or not isinstance(n_steps, (int, np.integer)):
        raise ValueError("n_steps must be an integer")
    if isinstance(pulse_steps, bool) or not isinstance(
        pulse_steps, (int, np.integer)
    ):
        raise ValueError("pulse_steps must be an integer")
    if n_steps < 1 or not 1 <= pulse_steps <= n_steps:
        raise ValueError("pulse_steps must lie in [1, n_steps]")
    if not math.isfinite(amplitude):
        raise ValueError("amplitude must be finite")
    values = np.zeros(int(n_steps), dtype=float)
    values[: int(pulse_steps)] = float(amplitude)
    return values


def _validated_inputs(
    grid: LocalMediatorGrid,
    source_values: Iterable[float],
    readout_positions: Iterable[float],
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    source = np.asarray(list(source_values), dtype=float)
    positions = np.asarray(list(readout_positions), dtype=float)
    if source.ndim != 1 or source.size < 1 or not np.isfinite(source).all():
        raise ValueError("source_values must be a non-empty finite sequence")
    if positions.ndim != 1 or positions.size < 1 or not np.isfinite(positions).all():
        raise ValueError("readout_positions must be a non-empty finite sequence")
    grid_coordinates = grid.coordinates
    if np.any(positions <= grid_coordinates[0]) or np.any(
        positions >= grid_coordinates[-1]
    ):
        raise ValueError("readout positions must lie strictly inside the grid")
    floating_indices = positions / float(grid.spacing) + float(grid.source_index)
    left_indices = np.floor(floating_indices).astype(int)
    fractions = floating_indices - left_indices
    return source, positions, left_indices, fractions


def _record_readouts(
    field: np.ndarray,
    left_indices: np.ndarray,
    fractions: np.ndarray,
) -> np.ndarray:
    left = field[left_indices]
    right = field[left_indices + 1]
    return left + fractions * (right - left)


def simulate_relaxation_diffusion_mediator(
    grid: LocalMediatorGrid,
    mediator: RelaxationDiffusionMediator,
    *,
    source_values: Iterable[float],
    readout_positions: Iterable[float],
) -> LocalMediatorTrace:
    """Propagate a source with an explicit local relaxation-diffusion update."""

    source, positions, left_indices, fractions = _validated_inputs(
        grid, source_values, readout_positions
    )
    diffusion_number = mediator.diffusivity * grid.time_step / grid.spacing**2
    decay_number = mediator.decay_rate * grid.time_step
    if diffusion_number > 0.5:
        raise ValueError("relaxation-diffusion update violates the 1D CFL bound")
    if 2.0 * diffusion_number + decay_number > 1.0:
        raise ValueError("relaxation-diffusion update has a negative center weight")

    field = np.zeros(grid.n_points, dtype=float)
    values = np.empty((source.size + 1, positions.size), dtype=float)
    values[0] = _record_readouts(field, left_indices, fractions)
    for step, source_value in enumerate(source, start=1):
        laplacian = field[:-2] - 2.0 * field[1:-1] + field[2:]
        updated = np.zeros_like(field)
        updated[1:-1] = (
            field[1:-1]
            + diffusion_number * laplacian
            - decay_number * field[1:-1]
        )
        updated[grid.source_index] += grid.time_step * source_value / grid.spacing
        field = updated
        values[step] = _record_readouts(field, left_indices, fractions)

    times = np.arange(source.size + 1, dtype=float) * grid.time_step
    return LocalMediatorTrace(
        model="relaxation_diffusion",
        times=times,
        readout_positions=positions,
        values=values,
        source_values=source,
    )


def simulate_telegraph_mediator(
    grid: LocalMediatorGrid,
    mediator: TelegraphMediator,
    *,
    source_values: Iterable[float],
    readout_positions: Iterable[float],
) -> LocalMediatorTrace:
    """Propagate a source with a local first-order field/momentum update."""

    source, positions, left_indices, fractions = _validated_inputs(
        grid, source_values, readout_positions
    )
    courant = mediator.wave_speed * grid.time_step / grid.spacing
    if courant > 1.0:
        raise ValueError("telegraph update violates the 1D Courant bound")
    if 2.0 * mediator.damping_rate * grid.time_step > 1.0:
        raise ValueError("telegraph damping is too large for the explicit update")
    if mediator.natural_frequency * grid.time_step > 1.0:
        raise ValueError("telegraph natural frequency is under-resolved")

    field = np.zeros(grid.n_points, dtype=float)
    momentum = np.zeros(grid.n_points, dtype=float)
    values = np.empty((source.size + 1, positions.size), dtype=float)
    values[0] = _record_readouts(field, left_indices, fractions)
    wave_factor = mediator.wave_speed**2 / grid.spacing**2
    restoring = mediator.natural_frequency**2
    for step, source_value in enumerate(source, start=1):
        laplacian = field[:-2] - 2.0 * field[1:-1] + field[2:]
        acceleration = (
            wave_factor * laplacian
            - 2.0 * mediator.damping_rate * momentum[1:-1]
            - restoring * field[1:-1]
        )
        updated_momentum = np.zeros_like(momentum)
        updated_momentum[1:-1] = momentum[1:-1] + grid.time_step * acceleration
        updated_momentum[grid.source_index] += (
            grid.time_step * source_value / grid.spacing
        )
        updated_field = np.zeros_like(field)
        updated_field[1:-1] = field[1:-1] + grid.time_step * updated_momentum[1:-1]
        momentum = updated_momentum
        field = updated_field
        values[step] = _record_readouts(field, left_indices, fractions)

    times = np.arange(source.size + 1, dtype=float) * grid.time_step
    return LocalMediatorTrace(
        model="telegraph",
        times=times,
        readout_positions=positions,
        values=values,
        source_values=source,
    )
