$ErrorActionPreference = "Stop"

$KindleDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$PaperRoot = Resolve-Path -LiteralPath (Join-Path $KindleDir "..")
$AssetDir = Join-Path $KindleDir "_kindle_assets"

$papers = @(
    @{
        Name = "paper_0_kindle"
        Source = Join-Path $PaperRoot "paper_0\main.tex"
        Graphics = "../paper_0/"
        Bibliography = "../paper_0/references"
        FigureReplacements = @{}
    },
    @{
        Name = "paper_i_long_kindle"
        Source = Join-Path $PaperRoot "paper_i\main.tex"
        Graphics = "../paper_i/"
        Bibliography = "../paper_i/references"
        FigureReplacements = @{
            "{fig_markov_embedding.pdf}" = "{_kindle_assets/paper_i_fig_markov_embedding.png}"
        }
    },
    @{
        Name = "paper_i_compact_kindle"
        Source = Join-Path $PaperRoot "paper_i\main_compact.tex"
        Graphics = "../paper_i/"
        Bibliography = "../paper_i/references"
        FigureReplacements = @{}
    },
    @{
        Name = "paper_ii_kindle"
        Source = Join-Path $PaperRoot "paper_ii\main.tex"
        Graphics = "../paper_ii/"
        Bibliography = "../paper_ii/references2"
        FigureReplacements = @{}
    }
)

function Convert-ToKindleTex {
    param(
        [Parameter(Mandatory = $true)][string]$SourceText,
        [Parameter(Mandatory = $true)][hashtable]$Paper
    )

    $text = [regex]::Replace(
        $SourceText,
        "\\documentclass\[(?<opts>[^\]]+)\]\{revtex4-2\}",
        {
            param($match)
            $opts = $match.Groups["opts"].Value -split "," |
                ForEach-Object { $_.Trim() } |
                Where-Object { $_ -and $_ -notin @("preprint", "reprint", "twocolumn", "10pt", "11pt", "12pt") }

            $deduped = New-Object System.Collections.Generic.List[string]
            foreach ($opt in @("preprint", "12pt") + $opts) {
                if (-not $deduped.Contains($opt)) {
                    $deduped.Add($opt)
                }
            }

            "\documentclass[$($deduped -join ',')]{revtex4-2}"
        },
        1
    )

    $kindlePreamble = @"

% Kindle/eReader reading layout. The source paper text is unchanged; only
% page geometry, line spacing, and graphics lookup are adapted.
\usepackage[paperwidth=108mm,paperheight=144mm,top=8mm,bottom=9mm,left=7mm,right=7mm]{geometry}
\usepackage{setspace}
\usepackage[hidelinks]{hyperref}
\graphicspath{{$($Paper.Graphics)}}
\linespread{1.04}
\AtBeginDocument{\sloppy\raggedbottom\setstretch{1.04}}
\setlength{\parskip}{0.12em}
\makeatletter
\renewcommand\section{\@startsection{section}{1}{\z@}{1.7ex plus .5ex minus .2ex}{0.8ex plus .2ex}{\normalfont\large\bfseries\raggedright}}
\renewcommand\subsection{\@startsection{subsection}{2}{\z@}{1.3ex plus .4ex minus .2ex}{0.6ex plus .2ex}{\normalfont\normalsize\bfseries\raggedright}}
\renewcommand\subsubsection{\@startsection{subsubsection}{3}{\z@}{1.1ex plus .3ex minus .2ex}{0.5ex plus .2ex}{\normalfont\normalsize\itshape\raggedright}}
\makeatother
"@

    $text = [regex]::Replace($text, "\\begin\{document\}", "$kindlePreamble`r`n\begin{document}", 1)
    $text = [regex]::Replace($text, "\\bibliography\{[^}]+\}", "\bibliography{$($Paper.Bibliography)}")

    foreach ($key in $Paper.FigureReplacements.Keys) {
        $text = $text.Replace($key, $Paper.FigureReplacements[$key])
    }

    "% Generated by paper/kindle/build_kindle_pdfs.ps1. Do not edit by hand.`r`n" + $text
}

function New-KindleAssets {
    New-Item -ItemType Directory -Force -Path $AssetDir | Out-Null

    $sourcePdf = Join-Path $PaperRoot "paper_i\fig_markov_embedding.pdf"
    $outputBase = Join-Path $AssetDir "paper_i_fig_markov_embedding"
    & pdftoppm -png -singlefile -r 180 $sourcePdf $outputBase
    if ($LASTEXITCODE -ne 0) { throw "pdftoppm failed for fig_markov_embedding.pdf" }

    $outputPng = Join-Path $AssetDir "paper_i_fig_markov_embedding.png"
    if (-not (Test-Path -LiteralPath $outputPng)) { throw "Expected asset was not created: $outputPng" }
}

Push-Location $KindleDir
try {
    New-KindleAssets

    foreach ($paper in $papers) {
        $sourceText = [System.IO.File]::ReadAllText($paper.Source)
        $kindleText = Convert-ToKindleTex -SourceText $sourceText -Paper $paper
        $texPath = Join-Path $KindleDir "$($paper.Name).tex"

        [System.IO.File]::WriteAllText($texPath, $kindleText, [System.Text.Encoding]::UTF8)

        & xelatex -interaction=nonstopmode -halt-on-error "$($paper.Name).tex"
        if ($LASTEXITCODE -ne 0) { throw "xelatex failed for $($paper.Name).tex" }

        & bibtex "$($paper.Name)"
        if ($LASTEXITCODE -ne 0) { throw "bibtex failed for $($paper.Name)" }

        & xelatex -interaction=nonstopmode -halt-on-error "$($paper.Name).tex"
        if ($LASTEXITCODE -ne 0) { throw "second xelatex failed for $($paper.Name).tex" }

        & xelatex -interaction=nonstopmode -halt-on-error "$($paper.Name).tex"
        if ($LASTEXITCODE -ne 0) { throw "third xelatex failed for $($paper.Name).tex" }
    }
}
finally {
    $cleanupPatterns = @("*.aux", "*.bbl", "*.blg", "*.fdb_latexmk", "*.fls", "*.log", "*.out", "*.synctex.gz", "*Notes.bib", "*_kindle.tex")
    foreach ($pattern in $cleanupPatterns) {
        Get-ChildItem -LiteralPath $KindleDir -Filter $pattern -ErrorAction SilentlyContinue |
            Remove-Item -Force -ErrorAction SilentlyContinue
    }
    if (Test-Path -LiteralPath $AssetDir) {
        Remove-Item -LiteralPath $AssetDir -Recurse -Force -ErrorAction SilentlyContinue
    }
    Pop-Location
}

Write-Host "Kindle PDFs written to $KindleDir"